apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: great-rabbit-java-springboot
  janus-idp.io/tekton: great-rabbit-java-springboot
  backstage.io/kubernetes-id: great-rabbit-java-springboot
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: great-rabbit-java-springboot
resources: 
- deployment.yaml
- route.yaml
- service.yaml
